# pubspec.yaml
name: my_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  geolocator: ^14.0.2
  firebase_core: ^2.4.1
  firebase_database: ^10.0.10
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
